export { searchMemory } from './retrieve/searchMemory';
export type { SearchInput, SearchResult, SearchEntity, SearchEdge, SearchEpisode } from './retrieve/searchMemory';
export { openMemoryCoreDb } from './db/connection';
export type { MemoryCoreDb } from './db/connection';
export { attachTrailDbReadOnly } from './db/attach';
export { createOllamaClient } from './ollama/client';
export type { OllamaClient } from './ollama/client';
export type { MemoryLogger } from './logger';
export { runConversationIncremental } from './pipeline/runConversationIncremental';
export type { IncrementalResult } from './pipeline/runConversationIncremental';
export { runConversationBackfill } from './pipeline/runConversationBackfill';
export type { BackfillResult } from './pipeline/runConversationBackfill';
export { runCodeIncremental } from './pipeline/runCodeIncremental';
export type { CodeIncrementalResult } from './pipeline/runCodeIncremental';
export { runBugHistoryIncremental } from './pipeline/runBugHistoryIncremental';
export type { BugHistoryIncrementalResult } from './pipeline/runBugHistoryIncremental';
export { ingestAstFacts } from './ingest/code/astFunctionLevel';
export type { AstFactInput, AstFactStats } from './ingest/code/astFunctionLevel';
export { extractDecisionComments } from './ingest/code/extractComments';
export type { ExtractCommentsInput, ExtractCommentsStats } from './ingest/code/extractComments';
export { extractCommitRationale } from './ingest/code/extractCommitRationale';
export type { ExtractRationaleInput, ExtractRationaleStats } from './ingest/code/extractCommitRationale';
export { runReviewIncremental } from './pipeline/runReviewIncremental';
export type { ReviewIncrementalResult } from './pipeline/runReviewIncremental';
export { ingestAgentReviewResult } from './ingest/review/ingestAgentReviewResult';
export type { IngestAgentReviewResult } from './ingest/review/ingestAgentReviewResult';
export { runAgentRunWatchdog } from './ingest/review/agentRunWatchdog';
export type { AgentRunWatchdogResult } from './ingest/review/agentRunWatchdog';
export { AgentReviewInputSchema, AgentReviewFindingSchema } from './types/AgentReviewInput';
export type { AgentReviewInput, AgentReviewFinding } from './types/AgentReviewInput';

export { runSpecIncremental } from './pipeline/runSpecIncremental';
export type { SpecIncrementalResult } from './pipeline/runSpecIncremental';

export { listRecurringBugs } from './retrieve/listRecurringBugs';
export type { RecurringBugGroup, BugFixSummary } from './retrieve/listRecurringBugs';
export { getBugHistory } from './retrieve/getBugHistory';
export type { BugHistoryEntry, CausedByRef } from './retrieve/getBugHistory';

export { listUnaddressedReviewFindings } from './retrieve/listUnaddressedReviewFindings';
export type { UnaddressedReviewFinding } from './retrieve/listUnaddressedReviewFindings';
export { getReviewHistory } from './retrieve/getReviewHistory';
export type { ReviewHistoryEntry, ReviewFindingSummary } from './retrieve/getReviewHistory';
export { linkReviewToCommit } from './retrieve/linkReviewToCommit';
export type { LinkReviewToCommitResult } from './retrieve/linkReviewToCommit';
