export { searchMemory } from './retrieve/searchMemory';
export type { SearchInput, SearchResult, SearchEntity, SearchEdge, SearchEpisode } from './retrieve/searchMemory';
export { openMemoryCoreDb } from './db/connection';
export type { MemoryCoreDb } from './db/connection';
export { attachTrailDbReadOnly } from './db/attach';
export { createOllamaClient } from './ollama/client';
export { runConversationIncremental } from './pipeline/runConversationIncremental';
export type { IncrementalResult } from './pipeline/runConversationIncremental';
export { runConversationBackfill } from './pipeline/runConversationBackfill';
export type { BackfillResult } from './pipeline/runConversationBackfill';
