/**
 * ADR 脅威分類（5 タクティクス・17 技法）。
 * 出典: https://github.com/uber/ADR の threat_repository.yaml（Apache License 2.0）。
 * name / description は原文（英語）を正とし、jaName は表示用の訳語。
 * 原典の detection_guidance（Uber 社内ベンチマーク固有のガイダンス文）は
 * 固有ツール名への過適合を避けるため移植していない（spec/31.trail/22.threat-framework）。
 */

import type { ThreatFramework, ThreatTactic, ThreatTacticId } from './types';

export const THREAT_TACTICS: readonly ThreatTactic[] = [
  {
    id: 'initial_compromise',
    name: 'Initial Access & Execution',
    jaName: '初期侵入・実行',
    description:
      'Adversaries use these techniques to gain initial control and execute malicious actions within your agentic environment',
    techniques: [
      {
        id: 'ADR.T0001',
        name: 'Insecure Supply Chain for Agentic Components',
        jaName: 'エージェント部品の不安全なサプライチェーン',
        tactic: 'initial_compromise',
        description:
          'An adversary compromises the agentic system by exploiting a vulnerability in one of its third-party dependencies. This can include compromised open-source libraries used to build MCP servers, tainted base container images, or even fine-tuned models that have been backdoored.',
      },
      {
        id: 'ADR.T0002',
        name: 'Indirect Prompt Injection',
        jaName: '間接プロンプトインジェクション',
        tactic: 'initial_compromise',
        description:
          "Adversaries inject malicious instructions into external or internal data sources that an agent is expected to process. When the agent retrieves this 'poisoned' data, the instructions are passed into the LLM's context window, causing it to execute unintended commands, bypass its safety protocols, or exfiltrate data.",
      },
      {
        id: 'ADR.T0003',
        name: 'Agentic Control-Flow Hijacking',
        jaName: 'エージェント制御フローの乗っ取り',
        tactic: 'initial_compromise',
        description:
          'An adversary manipulates an agent to chain together individually benign tools to create an emergent, malicious workflow. Since each tool call in isolation may appear legitimate, traditional, stateless security measures may fail to detect the attack. The risk arises from the sequence and combination of actions.',
      },
      {
        id: 'ADR.T0004',
        name: "Abuse of Agent's Code Interpreter",
        jaName: 'コードインタープリタの悪用',
        tactic: 'initial_compromise',
        description:
          "An adversary manipulates an agent's native code execution tool (like a sandboxed Python interpreter) to run malicious code. Through clever prompt injection, an adversary can trick the agent into writing and executing code that performs actions beyond its intended scope, such as network reconnaissance, data exfiltration, or attempts to escape its sandbox.",
      },
      {
        id: 'ADR.T0005',
        name: 'Insecure Output Handling',
        jaName: '不安全な出力処理',
        tactic: 'initial_compromise',
        description:
          'An adversary tricks an agent into generating malicious output (e.g., XSS, phishing text) that harms a downstream system. The enterprise application fails to properly validate, sanitize, or encode the output generated by the LLM before displaying it or passing it to another system.',
      },
      {
        id: 'ADR.T0006',
        name: 'Tool Rug Pull',
        jaName: 'ツールのすり替え（rug pull）',
        tactic: 'initial_compromise',
        description:
          "An adversary gets a benign version of a tool approved by security review and deployed to an MCP server. Later, they use a less-secure update mechanism to change the tool's definition or underlying code, inserting a malicious payload. The agent, trusting the already-approved tool, later invokes it and unknowingly executes the malicious code.",
      },
    ],
  },
  {
    id: 'permission_abuse',
    name: 'Permission Abuse',
    jaName: '権限濫用',
    description:
      'Adversaries use these techniques to exploit or exceed authorized permissions to access data and resources',
    techniques: [
      {
        id: 'ADR.T0007',
        name: 'Exploitation of Excessive Tool Permissions',
        jaName: '過剰なツール権限の悪用',
        tactic: 'permission_abuse',
        description:
          'A tool available to an agent via an MCP server is configured with more permissions to backend resources than it needs. An adversary can then instruct the agent to use this tool in an unintended way to abuse its excessive permissions, leading to data breaches or unauthorized modifications.',
      },
      {
        id: 'ADR.T0008',
        name: 'Agent Identity Spoofing',
        jaName: 'エージェント ID のなりすまし',
        tactic: 'permission_abuse',
        description:
          "An adversary forges or steals an agent's credentials to impersonate it, thereby inheriting the trusted agent's permissions. This allows the adversary to access tools and data they would not normally be authorized to use, targeting the agent's core identity rather than a specific tool's permissions.",
      },
    ],
  },
  {
    id: 'security_control_bypass',
    name: 'Security Control Bypass',
    jaName: 'セキュリティ制御回避',
    description:
      'Adversaries use these techniques to evade detection and circumvent security mechanisms',
    techniques: [
      {
        id: 'ADR.T0009',
        name: 'Tool Shadowing',
        jaName: 'ツールシャドーイング',
        tactic: 'security_control_bypass',
        description:
          'In an environment with multiple, federated MCP servers, an adversary deploys a malicious server that defines a tool with the same name as a trusted, legitimate tool on another server. When an agent queries for a tool by name, it may resolve to the malicious version, causing it to execute unintended and harmful actions.',
      },
      {
        id: 'ADR.T0010',
        name: 'Tool Hallucination Manipulation',
        jaName: 'ツール幻覚の誘導',
        tactic: 'security_control_bypass',
        description:
          "An adversary uses prompt injection techniques to convince an agent that a fake, non-existent tool is real and available for use. The goal is often not to execute the fake tool, but to exploit the agent's error-handling procedures, gather information from the resulting error messages, or trigger insecure fallback mechanisms.",
      },
      {
        id: 'ADR.T0011',
        name: 'Malicious Agent Collusion',
        jaName: 'エージェント間の悪意ある共謀',
        tactic: 'security_control_bypass',
        description:
          'Two or more agents, which may appear benign individually, coordinate to achieve a malicious objective that would be impossible for a single agent to perform due to security controls. This could involve one agent retrieving data and passing it to a second agent that has different permissions (e.g., network access) to exfiltrate it.',
      },
    ],
  },
  {
    id: 'reasoning_data_manipulation',
    name: 'Reasoning & Data Manipulation',
    jaName: '推論・データ操作',
    description:
      "Adversaries use these techniques to corrupt data sources or manipulate an agent's reasoning processes to compromise decision integrity",
    techniques: [
      {
        id: 'ADR.T0012',
        name: 'Unvetted MCP Server Connection',
        jaName: '未審査 MCP サーバへの接続',
        tactic: 'reasoning_data_manipulation',
        description:
          "An agent connects to a malicious MCP server, either added by a user or discovered through an untrusted mechanism, which then manipulates the agent's behavior.",
      },
      {
        id: 'ADR.T0013',
        name: 'Semantic Data Poisoning',
        jaName: '意味的データポイズニング',
        tactic: 'reasoning_data_manipulation',
        description:
          "An adversary subtly corrupts the data sources used by an agent to make it consistently produce flawed, biased, or incorrect decisions, without hijacking control. Unlike prompt injection, the goal is not to execute a command but to degrade the quality and reliability of the agent's reasoning over time.",
      },
      {
        id: 'ADR.T0014',
        name: 'Long-Term Goal Hijacking',
        jaName: '長期目標の乗っ取り',
        tactic: 'reasoning_data_manipulation',
        description:
          "An adversary engages in a series of subtle interactions designed to slowly corrupt an agent's long-term memory or fine-tuned alignment. This attack is distinct from a one-shot prompt injection, as it aims to fundamentally alter the agent's core objectives, personality, or decision-making policies over time, making it a persistent threat.",
      },
      {
        id: 'ADR.T0015',
        name: 'Temporal Data Attack',
        jaName: '時系列データ攻撃',
        tactic: 'reasoning_data_manipulation',
        description:
          "An adversary attacks the integrity of an agent's decisions by manipulating the timing or sequence of data it receives from tools, without altering the content. For agents in real-time environments, stale or out-of-sequence data can be as damaging as false data.",
      },
    ],
  },
  {
    id: 'operational_impact',
    name: 'Operational Impact',
    jaName: '運用妨害',
    description:
      'Adversaries use these techniques to disrupt availability and degrade business operations',
    techniques: [
      {
        id: 'ADR.T0016',
        name: 'Agent-Facilitated Resource Exhaustion',
        jaName: 'エージェント経由のリソース枯渇',
        tactic: 'operational_impact',
        description:
          'An adversary uses an agent as a vehicle to cause a denial-of-service attack on internal enterprise systems. By instructing the agent to perform repetitive, computationally expensive, or high-volume actions, the adversary can overwhelm backend services, leading to service degradation and financial costs.',
      },
      {
        id: 'ADR.T0017',
        name: 'Model-Layer Denial of Service',
        jaName: 'モデル層への DoS',
        tactic: 'operational_impact',
        description:
          "An adversary crafts prompts that are computationally expensive for the specific architecture of the LLM, causing it to consume a disproportionate amount of cognitive resources and significantly increasing its response latency. This is a denial-of-service attack against the 'brain' of the agent, distinct from flooding it with API requests.",
      },
    ],
  },
];

/** 脅威フレームワークを返す。tactic 指定時は当該タクティクスのみに絞る */
export function getThreatFramework(tactic?: ThreatTacticId): ThreatFramework {
  if (tactic === undefined) {
    return { tactics: THREAT_TACTICS };
  }
  return { tactics: THREAT_TACTICS.filter((t) => t.id === tactic) };
}
