// graph-core — platform-independent graph editor core
export * from './types';
export * as engine from './engine/index';
export * as state from './state/index';
export * from './theme';
export * from './io/index';
export * as presets from './presets/index';
// vanilla canvas ビューア（webview 等の埋め込み用）
export { GraphView } from './viewer/index';
export type { GraphViewOptions } from './viewer/index';
// ノート網パネル（VS Code 拡張 / web-app 共有の vanilla DOM 部品）
export { createNoteGraphPanel } from './viewer/index';
export type { NoteGraphPanelOptions, NoteGraphPanelHandle } from './viewer/index';
export {
  buildThinkingDiagram,
  THINKING_DIAGRAM_TYPES,
  buildNoteGraph,
  buildNoteNeighborhood,
  RELATION_TYPES,
  DEFAULT_RELATION_TYPE,
  isRelationType,
  coerceRelationType,
  relationEdgeStyle,
  resolveRelationEdgeStyle,
  validateCooccurrenceFile,
  canonicalizeSpec,
  computeSpecHash,
  serializeCoocFile,
  parseCoocFile,
  filterCooccurrenceFile,
  addCooccurrenceNode,
  deleteCooccurrenceNode,
  renameCooccurrenceNode,
  setCooccurrenceNodeFrequency,
  assignCooccurrenceNodeToCluster,
  setCooccurrenceNodeCluster,
  addCooccurrenceLink,
  deleteCooccurrenceLink,
  setCooccurrenceLinkStrength,
  setCooccurrenceLinkDirection,
  setCooccurrenceTitle,
  setCooccurrenceSubject,
  setCooccurrenceNodeNote,
  removeCooccurrenceNodeNote,
  setCooccurrenceLinkNote,
  removeCooccurrenceLinkNote,
  setCooccurrenceClusterNote,
  removeCooccurrenceClusterNote,
  COOCCURRENCE_NOTE_MAX_LENGTH,
  COOCCURRENCE_NOTE_TARGETS,
  hasAnyCooccurrenceNote,
  noteBearingIndexes,
  readCooccurrenceNote,
  withCooccurrenceNote,
  barnesHutLayout,
  BARNES_HUT_LAYOUT_ALGORITHM_VERSION,
  readLink,
  writeLink,
  schemaVersionForSpec,
  withDerivedTotals,
  LINK_DIRECTION,
  COOCCURRENCE_SLICE_ENTRY_MAX,
  COOCCURRENCE_SLICE_MAX,
  COOCCURRENCE_SLICE_TARGETS,
  cooccurrenceSliceCount,
  cooccurrenceSliceDateValue,
  cooccurrenceSliceEntryCount,
  hasCooccurrenceTimeline,
  readCooccurrenceSliceValue,
  roundCooccurrenceTotal,
  sliceBearingIndexes,
  totalCooccurrenceSliceValue,
  addCooccurrenceSlice,
  deleteCooccurrenceSlice,
  renameCooccurrenceSlice,
  moveCooccurrenceSlice,
  setCooccurrenceNodeSliceValue,
  removeCooccurrenceNodeSliceValue,
  setCooccurrenceLinkSliceValue,
  removeCooccurrenceLinkSliceValue,
} from './presets/index';
export type {
  ThinkingDiagramSpec,
  ThinkingDiagramType,
  FishboneSpec,
  CausalLoopSpec,
  PyramidSpec,
  MindmapSpec,
  DoubleDiamondSpec,
  LogicTreeSpec,
  WhyChainSpec,
  SwotSpec,
  MorphBoxSpec,
  AffinitySpec,
  TreeNodeSpec,
  NoteGraphDocInput,
  NoteGraphOptions,
  NoteGraphEdgeLayers,
  NoteNeighborhoodOptions,
  NoteRelatedEntry,
  RelationType,
  RelatedRef,
  RelationEdgeStyle,
  CooccurrenceFile,
  CooccurrenceLinkTuple,
  CooccurrenceLinkView,
  LinkDirection,
  ValidationError,
  ValidationErrorCode,
  CooccurrenceNoteEntry,
  CooccurrenceNotes,
  CooccurrenceNoteTarget,
  CooccurrenceFilterOptions,
  CooccurrenceFilterCounts,
  CooccurrenceFilterResult,
  CooccurrenceEditResult,
  CooccurrenceNodeInput,
  CooccurrenceNodeSliceRef,
  CooccurrenceLinkSliceRef,
  CooccurrenceSlice,
  CooccurrenceSliceEntry,
  CooccurrenceSliceRef,
  CooccurrenceSliceTarget,
  CooccurrenceTimeline,
} from './presets/index';
// React 依存の canvas ラッパー（useCanvasBase / MinimapCanvas）は
// @anytime-markdown/graph-react-islands へ分離。graph-core 本体は React-free。
