/**
 * 系図（ダイアグラム）の描画・編集に要る純ロジック。DOM もフレームワークも参照しない。
 *
 * 画面（`@anytime-markdown/diagram-viewer`）・拡張（`anytime-diagram`）・MCP サーバー
 * （`@anytime-markdown/mcp-diagram`）が同じ実装を読むことで、「画面で見た図」と「保存された図」
 * と「MCP が書いた図」が食い違わないようにする。
 */

export {
  anchorKey,
  arrowHeadPath,
  borderPoint,
  type ConnectorEnd,
  DEFAULT_CONNECTOR_LOOK,
  type ConnectorGeometry,
  connectorGeometry,
  familyLook,
  midpointOf,
  type ConnectorPointAt,
  MAX_CONNECTORS_PER_DIAGRAM,
  routePath,
  sameAnchor,
} from './connectors';
export { assertNever } from './exhaustive';
export {
  createEmptyDiagramDocument,
  diagramPeople,
  isEmptyLayout,
  MAX_PLACEMENTS_PER_DIAGRAM,
  nextConnectorId,
  nextElementName,
  parseDiagramDocument,
  parseDiagramFile,
  parseDiagramFileStrict,
  readDiagramAnchor,
  readDiagramLayout,
  type DiagramElementRemoval,
  removeDiagramConnectors,
  removeDiagramElement,
  renameDiagramElement,
  serializeDiagramDocument,
  setDiagramAnnotation,
  setDiagramFamilyGroup,
  validateDiagramDocument,
  validateDiagramLayout,
} from './document';
export {
  CELL_ADD_ICON_PX,
  columnBoundaryX,
  columnCentreX,
  fittingShift,
  freeCellsPath,
  type GridAxis,
  gridBounds,
  type GridCell,
  type GridExtent,
  gridExtent,
  type GridLineEdits,
  gridLineEdits,
  gridLineOccupant,
  insertGapEdit,
  type GridShift,
  GUTTER_ICON_PX,
  insertGridLine,
  isNoShift,
  MAX_GRID_CELLS,
  nearestCell,
  nearestFreeCell,
  NO_SHIFT,
  nudgeCell,
  nudgeShift,
  paintableExtent,
  removeGridLine,
  rowBoundaryY,
  rowCentreY,
  shiftCell,
  visibleCells,
  visibleGutterIndices,
} from './grid';
export {
  applyDiagramPlacements,
  applyDiagramSpacing,
  type AutomaticChart,
  type ChartEdge,
  type ChartNode,
  type ConnectorPoint,
  diagramChart,
  familyConnector,
  layoutDiagram,
  type PlacedChart,
} from './layout';
export {
  type ShapeOutline,
  SHAPE_OUTLINE_INSET,
  diagramShapeOf,
  shapeOutline,
  shapeTextInset,
} from './shapes';
export {
  cellFromPoint,
  cellKey,
  cellLimit,
  cellPosition,
  columnPitch,
  COORDINATE_LIMIT,
  gapBand,
  type GapAxis,
  DEFAULT_DIAGRAM_SPACING,
  DIAGRAM_MARGIN,
  DIAGRAM_SPACING_RANGE,
  isDefaultDiagramSpacing,
  isPlaceableCoordinate,
  readDiagramSpacing,
  resizedSpacing,
  rowPitch,
  spacedGaps,
} from './spacing';
export {
  DIAGRAM_ENDPOINTS,
  DIAGRAM_LINE_COLORS,
  DIAGRAM_LINE_ROUTES,
  DIAGRAM_LINE_STYLES,
  DIAGRAM_RELATIONS,
  DIAGRAM_SHAPES,
  DEFAULT_DIAGRAM_SHAPE,
  type DiagramAnchor,
  type DiagramConnector,
  type DiagramDocument,
  type DiagramEndpoint,
  type DiagramFamily,
  type DiagramGroupAxis,
  type DiagramLayout,
  type DiagramLineColor,
  type DiagramLineLook,
  type DiagramLineRoute,
  type DiagramLineStyle,
  type DiagramPlacement,
  type DiagramRelation,
  type DiagramShape,
  type DiagramSpacing,
  elementAnchor,
  EMPTY_DIAGRAM_LAYOUT,
  familyAnchor,
  lineAnchor,
} from './types';
export {
  chartPoint,
  type ChartView,
  editableSpacingKeys,
  fitChart,
  gapFromDrag,
  MAX_SCALE,
  MIN_SCALE,
  placementFromDrag,
  resizeFromDrag,
  SPACING_EDITABLE,
  zoomAt,
} from './view';
